### ISSUE TITLE
Unable to create a pull request

### ISSUE THREAD

**Issue by TamamoNoMae13** [minhducsun2002/skill#11]
Unable to create a pull request because the repository is empty.
Can't contribute anything to fix your skill issues.

**Comment by minhducsun2002** [comment]
how about you just make the repo non-empty

**Comment by TamamoNoMae13** [comment]
> how about you just make the repo non-empty

You cannot propose changes to an empty repo.

**Comment by minhducsun2002** [comment]
you can just go other way around and force it to be non-empty

**Comment by TamamoNoMae13** [comment]
> you can just go other way around and force it to be non-empty

how?

**Comment by minhducsun2002** [comment]
just break in github

**Comment by TamamoNoMae13** [comment]
> just break in github

Just create a branch. (It can be empty)

**Comment by minhducsun2002** [comment]
Won't.
