### ISSUE TITLE
VSC loads slower than PyCharm

### ISSUE THREAD

**Issue by justmangoou** [minhducsun2002/skill#13]
![image](https://user-images.githubusercontent.com/38831897/158813266-8ffd4ac8-38a6-40eb-9233-04d985d8b635.png)
![image](https://user-images.githubusercontent.com/38831897/158813303-8d1b90b6-e7d3-4c9d-ae11-959bcfbcebb7.png)

**Comment by AtelierMizumi** [comment]
![image](https://user-images.githubusercontent.com/95968103/158813428-f70c97ae-382b-4b5f-910e-12b042349452.png)

**Comment by minhducsun2002** [comment]
máy tao HDD bật VSC nhanh hơn bật não phản lực

**Comment by minhducsun2002** [comment]
my HDD machine launches VSC faster than the splash screen of any JB work

@AtelierMizumi you suck
