### ISSUE TITLE
Skill Issue relating to having skill issue

### ISSUE THREAD

**Issue by FukutoTojido** [minhducsun2002/skill#2]
The title should be self-explanatory. Since this issue is directly connected with skill, I would like to have skill issue actually be skill issue instead of skill issue.
If you are wondering what skill issue is, please check: https;//tryz.tryz.zzz/skill-issues#definition

**Comment by minhducsun2002** [comment]
DNS cannot resolve the domain

**Comment by minhducsun2002** [comment]
i think it is actually a networking issue

**Comment by minhducsun2002** [comment]
wait is it still skill issue

**Comment by FukutoTojido** [comment]
I would consider this a skill issue due to the host unability to connect to the server itself. If you cannot establish a proper connect to the server, it means that the code has been fucked up somewhere during execution procedure. Please double check your code again and fix the problem before closing this issue. Should any problem arise after this issue is closed, I'll open it again.

**Comment by NHaiAnh07** [comment]
did i

**Comment by huynd2001** [comment]
Arguably, given that there is nothing in this skill, one could argue that there's no skill issue at all. Hence, this issue can be closed.

**Comment by minhducsun2002** [comment]
I think having a skill issue could be a skill - therefore invalidating this issue.
