### ISSUE TITLE
Gravity Falls Theme Song issue

### ISSUE THREAD

**Issue by justmangoou** [minhducsun2002/skill#21]
![image](https://github.com/minhducsun2002/skill/assets/38831897/660a6cb3-6cfa-4d1f-ad23-3c9f69a2136d)

**Comment by TamamoNoMae13** [comment]
https://osu.ppy.sh/scores/osu/3314095605
Reproducable on my end. Can't even overwrite his score since 2020.

**Comment by justmangoou** [comment]
lmao ~150k score diff

**Comment by minhducsun2002** [comment]
Done.

![](https://cdn.discordapp.com/attachments/828620095633752105/1110594063373172858/screenshot734.png)
