### ISSUE TITLE
osu aim convert to csgo aim

### ISSUE THREAD

**Issue by NHaiAnh07** [minhducsun2002/skill#4]
just how

**Comment by minhducsun2002** [comment]
just snap at your teammate's head

**Comment by Gasmask-Chan** [comment]
xam lon vay cung hoi nua cai thang bac ky

**Comment by NHaiAnh07** [comment]
tao ko dc quyen hoi a

**Comment by Gasmask-Chan** [comment]
dung roi, hoi thi cung phai lua loi ma hoi. Hoi toan may cai cau ngu lon ca nuoc nhin vao deu biet la hai anh so 1 ngu

**Comment by minhducsun2002** [comment]
hai anh mac dinh ngu
