### ISSUE TITLE
my mouse isnt go straight

### ISSUE THREAD

**Issue by NHaiAnh07** [minhducsun2002/skill#9]
is it count as skill issue?

**Comment by genesheeesh** [comment]
nah your mouse just prefer being gay

**Comment by NHaiAnh07** [comment]
maybe that's the reason why my mouse isnt go straight

**Comment by minhducsun2002** [comment]
the user isn't straight, no mouse can fix that

**Comment by NHaiAnh07** [comment]
clgt

**Comment by justmangoou** [comment]
Because ur #1
